server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=BikeShopDB;encrypt=true;trustServerCertificate=true
    username: sa
    password: Sa@12345
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  # Mail Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: contact.basaucycle2026@gmail.com
    password: pjti mrad spub fhcg    # Google App Password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Cloudinary Configuration
cloudinary:
  cloud-name: dod2rhslh      # Thay bằng cloud name của bạn
  api-key: 452779535846727            # Thay bằng API key
  api-secret: hf1c5E8DyC2lwEUuPuxQyg1NyhU      # Thay bằng API secret

# JWT Configuration
jwt:
  signer-key: "S7RxfF0UMgBdOAfHdDjklZm7lF3rTLjqWNrDgcXsNqm8Yw3KeVf9aHbPnYcXzJhQ"  # Generate from https://generate-secret.vercel.app/64
  expiration: 3600  # 1 hour in seconds